name: shmpy
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - pip
  - scipy
  - pip:
      - tensorflow
      - keras
      - biopython
      - scikit-learn
      - https://github.com/thayerf/SHMModels.git